version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbit_mq_service
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
