version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbit_mq_service
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    command: --authentication-policy=mysql_native_password
    ports:
      - '33061:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: problem_statement
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminSecret
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    name: ps_mysql_data
    driver: local
